{% set name = "sphinx-togglebutton" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-togglebutton-{{ version }}.tar.gz
  sha256: 41cbe2f87459eade8dc5718bb56146e8e113a05fb97459b90472470f0d357b55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - docutils
    - python
    - sphinx

test:
  imports:
    - sphinx_togglebutton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/sphinx-togglebutton
  summary: Add a toggle button to items on a page.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anirrudh
    - chrisjsewell
